<?php
namespace theme_moon\output;
defined('MOODLE_INTERNAL') || die;
use local_moon\library\Framework;
use local_moon\library\Helper\Utilities;
class core_renderer extends \theme_boost\output\core_renderer {
    public function standard_head_html()
    {
        $content = parent::standard_head_html(); // TODO: Change the autogenerated stub
        // Moon Init
        $document = Framework::getDocument();
        $content .= $document->getMoonAssets();
        return $content;
    }

    public function htmlattributes() {
        $attributes = parent::htmlattributes();
        $attributes .= ' data-bs-theme="' . Framework::getTheme()->getColorMode() . '"';
        return $attributes;
    }
    public function standard_after_main_region_html(): string
    {
        $document = Framework::getDocument();
        $content = parent::standard_after_main_region_html();
        $content .= $document->renderFooter();
        return $content;
    }
}